### PR TITLE
Skip SubmarinerAgentDegraded check, as it might indicate old state

### PR DESCRIPTION
**Pull request by manosnoam**
Signed-off-by: nmanos <nmanos@redhat.com>

### CODE REVIEW

**Review by MaxBab — COMMENTED** [review]
Could you elaborate, please?
What do you mean by "might indicate old state"?

Could we check it some other way?

**Comment by redhat-openshift** [comment]
This is another attempt to fine tune the test for Submariner addon
conditions. Since there are several conditions, we need to check the most
recent one. Sometimes the SubmarinerAgentDegraded is true (not good) at the
beginning, but later there's another condition that indicates that the
resource is Available, even that there's an old condition (could be few
hours before) of that degradation that was left true.

So as long as the Availability and the gateway label conditions are true, I
think that Submariner state is good.

If that will not work, I'll re-enable SubmarinerAgentDegraded negative test.

**Comment by MaxBab** [comment]
Submariner components have several states of condition.
All of them are important to watch to ensure stability of the working submariner component.

I think it's important to verify that all of the conditions are in a good state.
And if some of the condition state unable to recover to a success state, an issue should be opened to a dev team.

**Review by MaxBab — APPROVED** [review]

**Comment by manosnoam** [comment]
Yes, but the degragated condition timestemp (e.g. 4 hours ago) makes me
think this is an old condition which is not indicating the current status
(e.g. condition Available = true 10 minutes ago).

**Comment by MaxBab** [comment]
I understand that.
So, in that case, the condition state of submariner for every state should be updated every X seconds/minutes.

**Pull request merged**
